from app.config import settings

REFRESH_COOKIE_NAME = settings.REFRESH_COOKIE_NAME
REFRESH_COOKIE_PATH = settings.REFRESH_COOKIE_PATH
REFRESH_COOKIE_SECURE = settings.APP_ENV == "production"
REFRESH_COOKIE_SAMESITE = settings.REFRESH_COOKIE_SAMESITE
