"""initial schema

Revision ID: 7d5535c754f7
Revises: 
Create Date: 2026-05-19 17:35:02.058767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d5535c754f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.Enum('vat_monthly', 'vat_bimonthly', 'advance_monthly', 'advance_bimonthly', 'annual_report', name='deadlineruletype'), nullable=False),
    sa.Column('due_day_of_month', sa.Integer(), nullable=False),
    sa.Column('offset_months', sa.Integer(), server_default='0', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('due_day_of_month BETWEEN 1 AND 31', name='ck_deadline_rule_due_day_range'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_deadline_rule_effective_range'),
    sa.CheckConstraint('offset_months >= 0', name='ck_deadline_rule_offset_months_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deadline_rule_type_effective', 'deadline_rules', ['rule_type', 'effective_from'], unique=False)
    op.create_index(op.f('ix_deadline_rules_rule_type'), 'deadline_rules', ['rule_type'], unique=False)
    op.create_index('uq_deadline_rule_open_ended', 'deadline_rules', ['rule_type'], unique=True, postgresql_where=sa.text('effective_to IS NULL'), sqlite_where=sa.text('effective_to IS NULL'))
    op.create_table('legal_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_number', sa.String(), nullable=False),
    sa.Column('id_number_type', sa.Enum('individual', 'corporation', 'passport', 'other', name='idnumbertype'), nullable=False),
    sa.Column('entity_type', sa.Enum('osek_patur', 'osek_murshe', 'company_ltd', 'employee', name='entitytype'), nullable=True),
    sa.Column('official_name', sa.String(), nullable=False),
    sa.Column('vat_reporting_frequency', sa.Enum('monthly', 'bimonthly', 'exempt', name='vattype'), nullable=True),
    sa.Column('advance_payment_frequency', sa.Enum('monthly', 'bimonthly', name='advance_payment_frequency'), nullable=True),
    sa.Column('vat_exempt_ceiling', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('advance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('advance_rate_updated_at', sa.Date(), nullable=True),
    sa.Column('annual_revenue', sa.Numeric(precision=15, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number_type', 'id_number', name='uq_legal_entity_registration_id')
    )
    op.create_index('ix_legal_entities_official_name', 'legal_entities', ['official_name'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('id_number', sa.String(), nullable=False),
    sa.Column('id_number_type', sa.Enum('individual', 'corporation', 'passport', 'other', name='idnumbertype'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_building_number', sa.String(), nullable=True),
    sa.Column('address_apartment', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_zip_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("id_number_type IN ('individual', 'passport', 'other')", name='ck_persons_id_number_type_not_corporation'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number_type', 'id_number', name='uq_person_identity_id')
    )
    op.create_index('ix_persons_full_name', 'persons', ['full_name'], unique=False)
    op.create_index('ix_persons_id_number', 'persons', ['id_number'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fire_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'fired', 'canceled', 'failed', name='reminderstatus'), nullable=False),
    sa.Column('action_type', sa.Enum('CREATE_TASK', 'SEND_NOTIFICATION', 'CREATE_TASK_AND_NOTIFY', name='reminderactiontype'), nullable=False),
    sa.Column('source_domain', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_task_id', sa.Integer(), nullable=True),
    sa.Column('notification_template_key', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('fired_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminders_status_fire_at', 'reminders', ['status', 'fire_at'], unique=False)
    op.create_index(op.f('ix_reminders_fire_at'), 'reminders', ['fire_at'], unique=False)
    op.create_index(op.f('ix_reminders_status'), 'reminders', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('role', sa.Enum('advisor', 'secretary', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'frozen', 'closed', name='businessstatus'), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('phone_override', sa.String(length=20), nullable=True),
    sa.Column('email_override', sa.String(length=254), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('restored_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_legal_entity_name_active', 'businesses', ['legal_entity_id', 'business_name'], unique=True, postgresql_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ix_business_status', 'businesses', ['status'], unique=False)
    op.create_index(op.f('ix_businesses_legal_entity_id'), 'businesses', ['legal_entity_id'], unique=False)
    op.execute(sa.schema.CreateSequence(sa.Sequence('client_office_number_seq', start=100001)))
    op.create_table('client_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('office_client_number', sa.Integer(), server_default=sa.text("nextval('client_office_number_seq')"), nullable=False),
    sa.Column('accountant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'frozen', 'closed', name='clientstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('restored_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accountant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_records_accountant_id'), 'client_records', ['accountant_id'], unique=False)
    op.create_index('ix_client_records_active_created_desc', 'client_records', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_client_records_legal_entity_id'), 'client_records', ['legal_entity_id'], unique=False)
    op.create_index('ix_client_records_legal_entity_id_active', 'client_records', ['legal_entity_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_client_records_office_client_number_active', 'client_records', ['office_client_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('entity_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_audit_type_id', 'entity_audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_entity_audit_logs_entity_id'), 'entity_audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_audit_logs_entity_type'), 'entity_audit_logs', ['entity_type'], unique=False)
    op.create_table('entity_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_notes_type_id', 'entity_notes', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_entity_id'), 'entity_notes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_notes_entity_type'), 'entity_notes', ['entity_type'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='idempotencystatus'), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key', 'route', 'user_id', name='pk_idempotency_keys')
    )
    op.create_table('person_legal_entity_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'authorized_signatory', 'controlling_shareholder', name='personlegalentityrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'legal_entity_id', 'role', name='uq_person_legal_entity_role')
    )
    op.create_index('ix_person_legal_entity_links_legal_entity_id', 'person_legal_entity_links', ['legal_entity_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'done', 'canceled', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='taskpriority'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_role', sa.Enum('advisor', 'secretary', name='userrole'), nullable=True),
    sa.Column('source_domain', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('action_key', sa.String(length=100), nullable=True),
    sa.Column('action_payload', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['canceled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_assigned_to_user_id', 'tasks', ['assigned_to_user_id'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_tasks_source', 'tasks', ['source_domain', 'source_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('tax_calendar_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obligation_type', sa.Enum('vat', 'advance_payment', 'annual_report', 'national_insurance', name='obligationtype'), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('period_months_count', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('deadline_rule_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(obligation_type = 'annual_report' AND period IS NULL) OR (obligation_type <> 'annual_report' AND period IS NOT NULL)", name='ck_tax_calendar_entry_period_nullability'),
    sa.CheckConstraint("(obligation_type = 'annual_report' AND period_months_count IS NULL) OR (obligation_type <> 'annual_report'     AND period_months_count IN (1, 2))", name='ck_tax_calendar_entry_months_count'),
    sa.ForeignKeyConstraint(['deadline_rule_id'], ['deadline_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_calendar_entries_year_obligation', 'tax_calendar_entries', ['tax_year', 'obligation_type'], unique=False)
    op.create_index(op.f('ix_tax_calendar_entries_deadline_rule_id'), 'tax_calendar_entries', ['deadline_rule_id'], unique=False)
    op.create_index(op.f('ix_tax_calendar_entries_due_date'), 'tax_calendar_entries', ['due_date'], unique=False)
    op.create_index(op.f('ix_tax_calendar_entries_obligation_type'), 'tax_calendar_entries', ['obligation_type'], unique=False)
    op.create_index('uq_tax_calendar_entry_annual', 'tax_calendar_entries', ['obligation_type', 'tax_year'], unique=True, postgresql_where=sa.text("obligation_type = 'annual_report'"), sqlite_where=sa.text("obligation_type = 'annual_report'"))
    op.create_index('uq_tax_calendar_entry_periodic', 'tax_calendar_entries', ['obligation_type', 'period', 'period_months_count'], unique=True, postgresql_where=sa.text("obligation_type <> 'annual_report'"), sqlite_where=sa.text("obligation_type <> 'annual_report'"))
    op.create_table('user_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Enum('login_success', 'login_failure', 'logout', 'user_created', 'user_updated', 'user_activated', 'user_deactivated', 'password_reset', name='auditaction'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failure', name='auditstatus'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_audit_logs_action'), 'user_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_actor_user_id'), 'user_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_created_at'), 'user_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_email'), 'user_audit_logs', ['email'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_status'), 'user_audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_target_user_id'), 'user_audit_logs', ['target_user_id'], unique=False)
    op.create_table('annual_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('client_type', sa.Enum('individual', 'self_employed', 'corporation', 'public_institution', 'partnership', 'control_holder', 'exempt_dealer', name='clientannualfilingtype'), nullable=False),
    sa.Column('form_type', sa.Enum('1301', '1214', '1215', name='primaryannualreportform'), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'collecting_docs', 'in_preparation', 'pending_client', 'submitted', 'closed', 'canceled', name='annualreportstatus'), nullable=False),
    sa.Column('deadline_type', sa.Enum('standard', 'extended', 'custom', name='filingdeadlinetype'), nullable=False),
    sa.Column('filing_deadline', sa.DateTime(), nullable=True),
    sa.Column('custom_deadline_note', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('ita_reference', sa.String(), nullable=True),
    sa.Column('assessment_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('refund_due', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_due', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('has_rental_income', sa.Boolean(), nullable=False),
    sa.Column('has_capital_gains', sa.Boolean(), nullable=False),
    sa.Column('has_foreign_income', sa.Boolean(), nullable=False),
    sa.Column('has_depreciation', sa.Boolean(), nullable=False),
    sa.Column('has_exempt_rental', sa.Boolean(), nullable=False),
    sa.Column('submission_method', sa.Enum('online', 'manual', 'representative', name='submissionmethod'), nullable=True),
    sa.Column('extension_reason', sa.Enum('military_service', 'health_reason', 'general', 'war_situation', name='extensionreason'), nullable=True),
    sa.Column('tax_calendar_entry_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tax_calendar_entry_id'], ['tax_calendar_entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_annual_report_assigned', 'annual_reports', ['assigned_to'], unique=False)
    op.create_index('idx_annual_report_calendar_entry_active', 'annual_reports', ['tax_calendar_entry_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_annual_report_client_record_year', 'annual_reports', ['client_record_id', 'tax_year'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_annual_report_deadline', 'annual_reports', ['filing_deadline'], unique=False)
    op.create_index('idx_annual_report_status', 'annual_reports', ['status'], unique=False)
    op.create_index('idx_annual_report_tax_year_status_active', 'annual_reports', ['tax_year', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_annual_reports_client_record_id'), 'annual_reports', ['client_record_id'], unique=False)
    op.create_index(op.f('ix_annual_reports_tax_calendar_entry_id'), 'annual_reports', ['tax_calendar_entry_id'], unique=False)
    op.create_table('authority_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.Enum('assessing_officer', 'vat_branch', 'national_insurance', 'other', name='contacttype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authority_contact_type', 'authority_contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_authority_contacts_client_record_id'), 'authority_contacts', ['client_record_id'], unique=False)
    op.create_table('binder_handovers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('received_by_name', sa.String(), nullable=False),
    sa.Column('handed_over_at', sa.Date(), nullable=False),
    sa.Column('until_period_year', sa.Integer(), nullable=False),
    sa.Column('until_period_month', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_handovers_client_record_id'), 'binder_handovers', ['client_record_id'], unique=False)
    op.create_table('binders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('binder_number', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('location_status', sa.Enum('in_office', 'ready_for_handover', 'handed_over', name='binder_location_status'), nullable=False),
    sa.Column('capacity_status', sa.Enum('open', 'full', name='binder_capacity_status'), nullable=False),
    sa.Column('ready_for_handover_at', sa.DateTime(), nullable=True),
    sa.Column('handed_over_at', sa.Date(), nullable=True),
    sa.Column('handover_recipient_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_binder_period_start', 'binders', ['period_start'], unique=False)
    op.create_index('idx_binder_location_status', 'binders', ['location_status'], unique=False)
    op.create_index('idx_binder_capacity_status', 'binders', ['capacity_status'], unique=False)
    op.create_index(op.f('ix_binders_client_record_id'), 'binders', ['client_record_id'], unique=False)
    op.create_index('uq_binder_number_per_client', 'binders', ['client_record_id', 'binder_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('vat_work_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('period_type', sa.Enum('monthly', 'bimonthly', 'exempt', name='vattype'), nullable=False),
    sa.Column('status', sa.Enum('pending_materials', 'material_received', 'data_entry_in_progress', 'ready_for_review', 'filed', 'canceled', name='vatworkitemstatus'), nullable=False),
    sa.Column('pending_materials_note', sa.Text(), nullable=True),
    sa.Column('total_output_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_input_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_output_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_input_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_justification', sa.Text(), nullable=True),
    sa.Column('submission_method', sa.Enum('online', 'manual', 'representative', name='submissionmethod'), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('filed_by', sa.Integer(), nullable=True),
    sa.Column('submission_reference', sa.String(length=100), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('amends_item_id', sa.Integer(), nullable=True),
    sa.Column('tax_calendar_entry_id', sa.Integer(), nullable=False),
    sa.Column('due_date_original', sa.Date(), nullable=True),
    sa.Column('due_date_effective', sa.Date(), nullable=True),
    sa.Column('due_date_override_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amends_item_id'], ['vat_work_items.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['filed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tax_calendar_entry_id'], ['tax_calendar_entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vat_work_items_calendar_entry_active', 'vat_work_items', ['tax_calendar_entry_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_vat_work_items_client_record_id'), 'vat_work_items', ['client_record_id'], unique=False)
    op.create_index('ix_vat_work_items_period', 'vat_work_items', ['period'], unique=False)
    op.create_index('ix_vat_work_items_status', 'vat_work_items', ['status'], unique=False)
    op.create_index(op.f('ix_vat_work_items_tax_calendar_entry_id'), 'vat_work_items', ['tax_calendar_entry_id'], unique=False)
    op.create_index('ix_vat_work_items_turnover_lookup', 'vat_work_items', ['client_record_id', 'period', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_vat_work_item_client_record_period', 'vat_work_items', ['client_record_id', 'period'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('advance_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('period_months_count', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_date_original', sa.Date(), nullable=True),
    sa.Column('due_date_effective', sa.Date(), nullable=True),
    sa.Column('due_date_override_reason', sa.String(length=500), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('turnover_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('advance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('override_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'partial', name='advancepaymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.Enum('bank_transfer', 'credit_card', 'check', 'direct_debit', 'cash', 'other', name='paymentmethod'), nullable=True),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('tax_calendar_entry_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('restored_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tax_calendar_entry_id'], ['tax_calendar_entries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_advance_payment_calendar_entry_active', 'advance_payments', ['tax_calendar_entry_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_advance_payment_client_record_period', 'advance_payments', ['client_record_id', 'period'], unique=False)
    op.create_index('idx_advance_payment_due_date', 'advance_payments', ['due_date'], unique=False)
    op.create_index('idx_advance_payment_period_active', 'advance_payments', ['period'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_advance_payment_status', 'advance_payments', ['status'], unique=False)
    op.create_index(op.f('ix_advance_payments_annual_report_id'), 'advance_payments', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_advance_payments_client_record_id'), 'advance_payments', ['client_record_id'], unique=False)
    op.create_index(op.f('ix_advance_payments_tax_calendar_entry_id'), 'advance_payments', ['tax_calendar_entry_id'], unique=False)
    op.create_index('uq_advance_payment_client_record_period_active', 'advance_payments', ['client_record_id', 'period'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('annual_report_credit_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('resident', 'academic_degree', 'discharged_soldier', 'new_immigrant', 'single_parent', name='creditpointreason'), nullable=False),
    sa.Column('points', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annual_report_id', 'reason', name='uq_credit_point_report_reason')
    )
    op.create_index(op.f('ix_annual_report_credit_points_annual_report_id'), 'annual_report_credit_points', ['annual_report_id'], unique=False)
    op.create_table('annual_report_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('pension_contribution', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('donation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_credits', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('client_approved_at', sa.DateTime(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('amendment_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['annual_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('annual_report_income_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('business', 'salary', 'interest', 'dividends', 'capital_gains', 'rental', 'foreign', 'pension', 'other', name='incomesourcetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_annual_report_income_lines_amount_non_negative'),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_report_income_lines_annual_report_id'), 'annual_report_income_lines', ['annual_report_id'], unique=False)
    op.create_table('annual_report_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.Enum('schedule_a', 'schedule_b', 'schedule_gimmel', 'schedule_dalet', 'form_150', 'form_1504', 'form_6111', 'form_1344', 'form_1399', 'form_1350', 'form_1327', 'form_1342', 'form_1343', 'form_1348', 'form_858', name='annualreportschedule'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annual_report_id', 'schedule', name='uq_annual_report_schedules_report_schedule')
    )
    op.create_index(op.f('ix_annual_report_schedules_annual_report_id'), 'annual_report_schedules', ['annual_report_id'], unique=False)
    op.create_table('annual_report_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('not_started', 'collecting_docs', 'in_preparation', 'pending_client', 'submitted', 'closed', 'canceled', name='annualreportstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('not_started', 'collecting_docs', 'in_preparation', 'pending_client', 'submitted', 'closed', 'canceled', name='annualreportstatus'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_report_status_history_annual_report_id'), 'annual_report_status_history', ['annual_report_id'], unique=False)
    op.create_table('binder_handover_binders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('handover_id', sa.Integer(), nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['handover_id'], ['binder_handovers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_handover_binder_unique', 'binder_handover_binders', ['handover_id', 'binder_id'], unique=True)
    op.create_index(op.f('ix_binder_handover_binders_binder_id'), 'binder_handover_binders', ['binder_id'], unique=False)
    op.create_index(op.f('ix_binder_handover_binders_handover_id'), 'binder_handover_binders', ['handover_id'], unique=False)
    op.create_table('binder_intakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.Date(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_intakes_binder_id'), 'binder_intakes', ['binder_id'], unique=False)
    op.create_table('binder_lifecycle_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_lifecycle_logs_binder_id'), 'binder_lifecycle_logs', ['binder_id'], unique=False)
    op.create_table('charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('charge_type', sa.Enum('monthly_retainer', 'annual_report_fee', 'vat_filing_fee', 'representation_fee', 'consultation_fee', 'other', name='chargetype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'paid', 'canceled', name='chargestatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('months_covered', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['canceled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_charge_client_record_period', 'charges', ['client_record_id', 'period'], unique=False)
    op.create_index('idx_charge_status', 'charges', ['status'], unique=False)
    op.create_index(op.f('ix_charges_annual_report_id'), 'charges', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_charges_business_id'), 'charges', ['business_id'], unique=False)
    op.create_index(op.f('ix_charges_client_record_id'), 'charges', ['client_record_id'], unique=False)
    op.create_index(op.f('ix_charges_period'), 'charges', ['period'], unique=False)
    op.create_table('correspondence_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('correspondence_type', sa.Enum('call', 'letter', 'email', 'meeting', 'fax', name='correspondencetype'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['authority_contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_correspondence_business_occurred', 'correspondence_entries', ['business_id', 'occurred_at'], unique=False)
    op.create_index('idx_correspondence_occurred', 'correspondence_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_correspondence_entries_business_id'), 'correspondence_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_correspondence_entries_client_record_id'), 'correspondence_entries', ['client_record_id'], unique=False)
    op.create_index(op.f('ix_correspondence_entries_contact_id'), 'correspondence_entries', ['contact_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('binder_id', sa.Integer(), nullable=True),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.Enum('binder_received', 'binder_ready_for_handover', 'handover_reminder', 'annual_report_client_reminder', 'manual_payment_reminder', name='notificationtrigger'), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'email', name='notificationchannel'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'urgent', 'critical', name='notificationseverity'), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_business_status', 'notifications', ['business_id', 'status'], unique=False)
    op.create_index('idx_notification_client_record_status', 'notifications', ['client_record_id', 'status'], unique=False)
    op.create_index('idx_notification_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_status', 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_annual_report_id'), 'notifications', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_notifications_binder_id'), 'notifications', ['binder_id'], unique=False)
    op.create_index(op.f('ix_notifications_business_id'), 'notifications', ['business_id'], unique=False)
    op.create_index(op.f('ix_notifications_client_record_id'), 'notifications', ['client_record_id'], unique=False)
    op.create_table('permanent_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Enum('client', 'business', name='documentscope'), nullable=False),
    sa.Column('document_type', sa.Enum('id_copy', 'power_of_attorney', 'engagement_agreement', 'tax_form', 'receipt', 'invoice_doc', 'bank_approval', 'withholding_certificate', 'nii_approval', 'other', name='documenttype'), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('tax_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'received', 'approved', 'rejected', name='documentstatus'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(scope = 'client') OR (scope = 'business' AND business_id IS NOT NULL)", name='ck_document_business_scope_requires_business_id'),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['permanent_documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permanent_documents_business', 'permanent_documents', ['business_id', 'document_type', 'tax_year'], unique=False)
    op.create_index(op.f('ix_permanent_documents_business_id'), 'permanent_documents', ['business_id'], unique=False)
    op.create_index(op.f('ix_permanent_documents_client_record_id'), 'permanent_documents', ['client_record_id'], unique=False)
    op.create_index('ix_permanent_documents_client_record_type_year', 'permanent_documents', ['client_record_id', 'document_type', 'tax_year'], unique=False)
    op.create_index(op.f('ix_permanent_documents_tax_year'), 'permanent_documents', ['tax_year'], unique=False)
    op.create_table('vat_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('business_activity_id', sa.Integer(), nullable=True),
    sa.Column('invoice_type', sa.Enum('income', 'expense', name='invoicetype'), nullable=False),
    sa.Column('document_type', sa.Enum('tax_invoice', 'transaction_invoice', 'receipt', 'consolidated', 'self_invoice', 'credit_note', name='vatdocumenttype'), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('counterparty_name', sa.String(), nullable=False),
    sa.Column('counterparty_id', sa.String(), nullable=True),
    sa.Column('counterparty_id_type', sa.Enum('il_business', 'il_personal', 'foreign', 'anonymous', name='counterpartyidtype'), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_category', sa.Enum('inventory', 'office', 'travel', 'professional_services', 'equipment', 'rent', 'salary', 'marketing', 'vehicle', 'fuel', 'vehicle_maintenance', 'vehicle_insurance', 'vehicle_leasing', 'tolls_and_parking', 'entertainment', 'gifts', 'communication', 'insurance', 'maintenance', 'municipal_tax', 'utilities', 'postage_and_shipping', 'bank_fees', 'mixed_expense', name='expensecategory'), nullable=True),
    sa.Column('rate_type', sa.Enum('standard', 'exempt', 'zero_rate', name='vatratetype'), nullable=False),
    sa.Column('deduction_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_exceptional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['business_activity_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['vat_work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'invoice_type', 'invoice_number', name='uq_vat_invoice_item_type_number')
    )
    op.create_index(op.f('ix_vat_invoices_business_activity_id'), 'vat_invoices', ['business_activity_id'], unique=False)
    op.create_index('ix_vat_invoices_date', 'vat_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_vat_invoices_work_item_id'), 'vat_invoices', ['work_item_id'], unique=False)
    op.create_index('ix_vat_invoices_work_item_type', 'vat_invoices', ['work_item_id', 'invoice_type'], unique=False)
    op.create_table('annual_report_annex_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_entry_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_entry_id'], ['annual_report_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_entry_id', 'line_number', name='uq_annual_report_annex_data_schedule_entry_line')
    )
    op.create_index(op.f('ix_annual_report_annex_data_schedule_entry_id'), 'annual_report_annex_data', ['schedule_entry_id'], unique=False)
    op.create_table('annual_report_expense_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('office_rent', 'professional_services', 'salaries', 'depreciation', 'vehicle', 'marketing', 'insurance', 'communication', 'travel', 'training', 'bank_fees', 'other', name='expensecategorytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recognition_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('external_document_reference', sa.String(length=255), nullable=True),
    sa.Column('supporting_document_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supporting_document_id'], ['permanent_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_report_expense_lines_annual_report_id'), 'annual_report_expense_lines', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_annual_report_expense_lines_supporting_document_id'), 'annual_report_expense_lines', ['supporting_document_id'], unique=False)
    op.create_table('binder_intake_edit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['binder_intakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_intake_edit_logs_intake_id'), 'binder_intake_edit_logs', ['intake_id'], unique=False)
    op.create_table('binder_intake_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('material_type', sa.Enum('vat', 'income_tax', 'annual_report', 'salary', 'bookkeeping', 'national_insurance', 'capital_declaration', 'pension_and_insurance', 'corporate_docs', 'tax_assessment', 'other', name='materialtype'), nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('vat_report_id', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month_start', sa.Integer(), nullable=False),
    sa.Column('period_month_end', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['binder_intakes.id'], ),
    sa.ForeignKeyConstraint(['vat_report_id'], ['vat_work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intake_material_business', 'binder_intake_materials', ['business_id'], unique=False)
    op.create_index('idx_intake_material_type', 'binder_intake_materials', ['material_type'], unique=False)
    op.create_index(op.f('ix_binder_intake_materials_annual_report_id'), 'binder_intake_materials', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_binder_intake_materials_business_id'), 'binder_intake_materials', ['business_id'], unique=False)
    op.create_index(op.f('ix_binder_intake_materials_intake_id'), 'binder_intake_materials', ['intake_id'], unique=False)
    op.create_index(op.f('ix_binder_intake_materials_vat_report_id'), 'binder_intake_materials', ['vat_report_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_invoice_id', sa.String(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_charge_id'), 'invoices', ['charge_id'], unique=True)
    op.create_table('signature_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_record_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.Enum('engagement_agreement', 'annual_report_approval', 'power_of_attorney', 'vat_return_approval', 'custom', name='signaturerequesttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('signer_name', sa.String(), nullable=False),
    sa.Column('signer_email', sa.String(), nullable=True),
    sa.Column('signer_phone', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending_signature', 'signed', 'declined', 'expired', 'canceled', name='signaturerequeststatus'), nullable=False),
    sa.Column('signing_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_days', sa.Integer(), server_default='14', nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('signer_ip_address', sa.String(), nullable=True),
    sa.Column('signer_user_agent', sa.String(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('signed_document_key', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['canceled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_record_id'], ['client_records.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['permanent_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signing_token')
    )
    op.create_index('idx_sig_request_annual_report', 'signature_requests', ['annual_report_id'], unique=False)
    op.create_index('idx_sig_request_business', 'signature_requests', ['business_id'], unique=False)
    op.create_index('idx_sig_request_client_record', 'signature_requests', ['client_record_id'], unique=False)
    op.create_index('idx_sig_request_pending_sent_active', 'signature_requests', ['status', 'sent_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_sig_request_status', 'signature_requests', ['status'], unique=False)
    op.create_index(op.f('ix_signature_requests_annual_report_id'), 'signature_requests', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_business_id'), 'signature_requests', ['business_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_client_record_id'), 'signature_requests', ['client_record_id'], unique=False)
    op.create_table('vat_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['vat_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['vat_work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_audit_logs_invoice_id'), 'vat_audit_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_vat_audit_logs_work_item_id'), 'vat_audit_logs', ['work_item_id'], unique=False)
    op.create_table('signature_audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signature_request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signature_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sig_audit_occurred', 'signature_audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_signature_audit_events_signature_request_id'), 'signature_audit_events', ['signature_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_audit_events_signature_request_id'), table_name='signature_audit_events')
    op.drop_index('idx_sig_audit_occurred', table_name='signature_audit_events')
    op.drop_table('signature_audit_events')
    op.drop_index(op.f('ix_vat_audit_logs_work_item_id'), table_name='vat_audit_logs')
    op.drop_index(op.f('ix_vat_audit_logs_invoice_id'), table_name='vat_audit_logs')
    op.drop_table('vat_audit_logs')
    op.drop_index(op.f('ix_signature_requests_client_record_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_business_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_annual_report_id'), table_name='signature_requests')
    op.drop_index('idx_sig_request_status', table_name='signature_requests')
    op.drop_index('idx_sig_request_pending_sent_active', table_name='signature_requests', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_sig_request_client_record', table_name='signature_requests')
    op.drop_index('idx_sig_request_business', table_name='signature_requests')
    op.drop_index('idx_sig_request_annual_report', table_name='signature_requests')
    op.drop_table('signature_requests')
    op.drop_index(op.f('ix_invoices_charge_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_binder_intake_materials_vat_report_id'), table_name='binder_intake_materials')
    op.drop_index(op.f('ix_binder_intake_materials_intake_id'), table_name='binder_intake_materials')
    op.drop_index(op.f('ix_binder_intake_materials_business_id'), table_name='binder_intake_materials')
    op.drop_index(op.f('ix_binder_intake_materials_annual_report_id'), table_name='binder_intake_materials')
    op.drop_index('idx_intake_material_type', table_name='binder_intake_materials')
    op.drop_index('idx_intake_material_business', table_name='binder_intake_materials')
    op.drop_table('binder_intake_materials')
    op.drop_index(op.f('ix_binder_intake_edit_logs_intake_id'), table_name='binder_intake_edit_logs')
    op.drop_table('binder_intake_edit_logs')
    op.drop_index(op.f('ix_annual_report_expense_lines_supporting_document_id'), table_name='annual_report_expense_lines')
    op.drop_index(op.f('ix_annual_report_expense_lines_annual_report_id'), table_name='annual_report_expense_lines')
    op.drop_table('annual_report_expense_lines')
    op.drop_index(op.f('ix_annual_report_annex_data_schedule_entry_id'), table_name='annual_report_annex_data')
    op.drop_table('annual_report_annex_data')
    op.drop_index('ix_vat_invoices_work_item_type', table_name='vat_invoices')
    op.drop_index(op.f('ix_vat_invoices_work_item_id'), table_name='vat_invoices')
    op.drop_index('ix_vat_invoices_date', table_name='vat_invoices')
    op.drop_index(op.f('ix_vat_invoices_business_activity_id'), table_name='vat_invoices')
    op.drop_table('vat_invoices')
    op.drop_index(op.f('ix_permanent_documents_tax_year'), table_name='permanent_documents')
    op.drop_index('ix_permanent_documents_client_record_type_year', table_name='permanent_documents')
    op.drop_index(op.f('ix_permanent_documents_client_record_id'), table_name='permanent_documents')
    op.drop_index(op.f('ix_permanent_documents_business_id'), table_name='permanent_documents')
    op.drop_index('ix_permanent_documents_business', table_name='permanent_documents')
    op.drop_table('permanent_documents')
    op.drop_index(op.f('ix_notifications_client_record_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_business_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_binder_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_annual_report_id'), table_name='notifications')
    op.drop_index('idx_notification_status', table_name='notifications')
    op.drop_index('idx_notification_created_at', table_name='notifications')
    op.drop_index('idx_notification_client_record_status', table_name='notifications')
    op.drop_index('idx_notification_business_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_correspondence_entries_contact_id'), table_name='correspondence_entries')
    op.drop_index(op.f('ix_correspondence_entries_client_record_id'), table_name='correspondence_entries')
    op.drop_index(op.f('ix_correspondence_entries_business_id'), table_name='correspondence_entries')
    op.drop_index('idx_correspondence_occurred', table_name='correspondence_entries')
    op.drop_index('idx_correspondence_business_occurred', table_name='correspondence_entries')
    op.drop_table('correspondence_entries')
    op.drop_index(op.f('ix_charges_period'), table_name='charges')
    op.drop_index(op.f('ix_charges_client_record_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_business_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_annual_report_id'), table_name='charges')
    op.drop_index('idx_charge_status', table_name='charges')
    op.drop_index('idx_charge_client_record_period', table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_binder_lifecycle_logs_binder_id'), table_name='binder_lifecycle_logs')
    op.drop_table('binder_lifecycle_logs')
    op.drop_index(op.f('ix_binder_intakes_binder_id'), table_name='binder_intakes')
    op.drop_table('binder_intakes')
    op.drop_index(op.f('ix_binder_handover_binders_handover_id'), table_name='binder_handover_binders')
    op.drop_index(op.f('ix_binder_handover_binders_binder_id'), table_name='binder_handover_binders')
    op.drop_index('idx_handover_binder_unique', table_name='binder_handover_binders')
    op.drop_table('binder_handover_binders')
    op.drop_index(op.f('ix_annual_report_status_history_annual_report_id'), table_name='annual_report_status_history')
    op.drop_table('annual_report_status_history')
    op.drop_index(op.f('ix_annual_report_schedules_annual_report_id'), table_name='annual_report_schedules')
    op.drop_table('annual_report_schedules')
    op.drop_index(op.f('ix_annual_report_income_lines_annual_report_id'), table_name='annual_report_income_lines')
    op.drop_table('annual_report_income_lines')
    op.drop_table('annual_report_details')
    op.drop_index(op.f('ix_annual_report_credit_points_annual_report_id'), table_name='annual_report_credit_points')
    op.drop_table('annual_report_credit_points')
    op.drop_index('uq_advance_payment_client_record_period_active', table_name='advance_payments', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_advance_payments_tax_calendar_entry_id'), table_name='advance_payments')
    op.drop_index(op.f('ix_advance_payments_client_record_id'), table_name='advance_payments')
    op.drop_index(op.f('ix_advance_payments_annual_report_id'), table_name='advance_payments')
    op.drop_index('idx_advance_payment_status', table_name='advance_payments')
    op.drop_index('idx_advance_payment_period_active', table_name='advance_payments', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_advance_payment_due_date', table_name='advance_payments')
    op.drop_index('idx_advance_payment_client_record_period', table_name='advance_payments')
    op.drop_index('idx_advance_payment_calendar_entry_active', table_name='advance_payments', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_table('advance_payments')
    op.drop_index('uq_vat_work_item_client_record_period', table_name='vat_work_items', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_vat_work_items_turnover_lookup', table_name='vat_work_items', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_vat_work_items_tax_calendar_entry_id'), table_name='vat_work_items')
    op.drop_index('ix_vat_work_items_status', table_name='vat_work_items')
    op.drop_index('ix_vat_work_items_period', table_name='vat_work_items')
    op.drop_index(op.f('ix_vat_work_items_client_record_id'), table_name='vat_work_items')
    op.drop_index('idx_vat_work_items_calendar_entry_active', table_name='vat_work_items', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_table('vat_work_items')
    op.drop_index('uq_binder_number_per_client', table_name='binders', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_binders_client_record_id'), table_name='binders')
    op.drop_index('idx_binder_capacity_status', table_name='binders')
    op.drop_index('idx_binder_location_status', table_name='binders')
    op.drop_index('idx_binder_period_start', table_name='binders')
    op.drop_table('binders')
    op.drop_index(op.f('ix_binder_handovers_client_record_id'), table_name='binder_handovers')
    op.drop_table('binder_handovers')
    op.drop_index(op.f('ix_authority_contacts_client_record_id'), table_name='authority_contacts')
    op.drop_index('idx_authority_contact_type', table_name='authority_contacts')
    op.drop_table('authority_contacts')
    op.drop_index(op.f('ix_annual_reports_tax_calendar_entry_id'), table_name='annual_reports')
    op.drop_index(op.f('ix_annual_reports_client_record_id'), table_name='annual_reports')
    op.drop_index('idx_annual_report_tax_year_status_active', table_name='annual_reports', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_annual_report_status', table_name='annual_reports')
    op.drop_index('idx_annual_report_deadline', table_name='annual_reports')
    op.drop_index('idx_annual_report_client_record_year', table_name='annual_reports', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_annual_report_calendar_entry_active', table_name='annual_reports', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_annual_report_assigned', table_name='annual_reports')
    op.drop_table('annual_reports')
    op.drop_index(op.f('ix_user_audit_logs_target_user_id'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_status'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_email'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_created_at'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_actor_user_id'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_action'), table_name='user_audit_logs')
    op.drop_table('user_audit_logs')
    op.drop_index('uq_tax_calendar_entry_periodic', table_name='tax_calendar_entries', postgresql_where=sa.text("obligation_type <> 'annual_report'"), sqlite_where=sa.text("obligation_type <> 'annual_report'"))
    op.drop_index('uq_tax_calendar_entry_annual', table_name='tax_calendar_entries', postgresql_where=sa.text("obligation_type = 'annual_report'"), sqlite_where=sa.text("obligation_type = 'annual_report'"))
    op.drop_index(op.f('ix_tax_calendar_entries_obligation_type'), table_name='tax_calendar_entries')
    op.drop_index(op.f('ix_tax_calendar_entries_due_date'), table_name='tax_calendar_entries')
    op.drop_index(op.f('ix_tax_calendar_entries_deadline_rule_id'), table_name='tax_calendar_entries')
    op.drop_index('idx_tax_calendar_entries_year_obligation', table_name='tax_calendar_entries')
    op.drop_table('tax_calendar_entries')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_source', table_name='tasks')
    op.drop_index('idx_tasks_priority', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_assigned_to_user_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_person_legal_entity_links_legal_entity_id', table_name='person_legal_entity_links')
    op.drop_table('person_legal_entity_links')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_entity_notes_entity_type'), table_name='entity_notes')
    op.drop_index(op.f('ix_entity_notes_entity_id'), table_name='entity_notes')
    op.drop_index('idx_entity_notes_type_id', table_name='entity_notes')
    op.drop_table('entity_notes')
    op.drop_index(op.f('ix_entity_audit_logs_entity_type'), table_name='entity_audit_logs')
    op.drop_index(op.f('ix_entity_audit_logs_entity_id'), table_name='entity_audit_logs')
    op.drop_index('idx_entity_audit_type_id', table_name='entity_audit_logs')
    op.drop_table('entity_audit_logs')
    op.drop_index('ix_client_records_office_client_number_active', table_name='client_records', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_client_records_legal_entity_id_active', table_name='client_records', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_client_records_legal_entity_id'), table_name='client_records')
    op.drop_index('ix_client_records_active_created_desc', table_name='client_records', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_client_records_accountant_id'), table_name='client_records')
    op.drop_table('client_records')
    op.execute(sa.schema.DropSequence(sa.Sequence('client_office_number_seq')))
    op.drop_index(op.f('ix_businesses_legal_entity_id'), table_name='businesses')
    op.drop_index('ix_business_status', table_name='businesses')
    op.drop_index('ix_business_legal_entity_name_active', table_name='businesses', postgresql_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'))
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reminders_status'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_fire_at'), table_name='reminders')
    op.drop_index('idx_reminders_status_fire_at', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('ix_persons_id_number', table_name='persons')
    op.drop_index('ix_persons_full_name', table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_legal_entities_official_name', table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_index('uq_deadline_rule_open_ended', table_name='deadline_rules', postgresql_where=sa.text('effective_to IS NULL'), sqlite_where=sa.text('effective_to IS NULL'))
    op.drop_index(op.f('ix_deadline_rules_rule_type'), table_name='deadline_rules')
    op.drop_index('idx_deadline_rule_type_effective', table_name='deadline_rules')
    op.drop_table('deadline_rules')
    # ### end Alembic commands ###
