"""add_ready_for_pickup_at_to_binders

Revision ID: 966f3c2d3267
Revises: 0002
Create Date: 2026-04-28 14:00:49.282411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966f3c2d3267'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annual_report_status_history', 'changed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('annual_report_status_history', 'changed_by_name')
    op.drop_index(op.f('idx_intake_edit_log_intake'), table_name='binder_intake_edit_logs')
    op.add_column('binders', sa.Column('ready_for_pickup_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_sig_audit_request'), table_name='signature_audit_events')
    op.drop_index(op.f('idx_sig_request_token'), table_name='signature_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sig_request_token'), 'signature_requests', ['signing_token'], unique=True)
    op.create_index(op.f('idx_sig_audit_request'), 'signature_audit_events', ['signature_request_id'], unique=False)
    op.drop_column('binders', 'ready_for_pickup_at')
    op.create_index(op.f('idx_intake_edit_log_intake'), 'binder_intake_edit_logs', ['intake_id'], unique=False)
    op.add_column('annual_report_status_history', sa.Column('changed_by_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('annual_report_status_history', 'changed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
