"""make_binder_intake_material_period_fields_non_nullable

Revision ID: 8e7ee9ba46e0
Revises: 0003_remove_archived_vat_work_item_status
Create Date: 2026-05-17 15:14:42.903823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7ee9ba46e0'
down_revision: Union[str, Sequence[str], None] = '0003_remove_archived_vat_work_item_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('binder_intake_materials', 'period_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('binder_intake_materials', 'period_month_start',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('binder_intake_materials', 'period_month_end',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('binder_intake_materials', 'period_month_end',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('binder_intake_materials', 'period_month_start',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('binder_intake_materials', 'period_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
