"""add official_name to legal_entities

Revision ID: 1599624f006f
Revises: 0021_add_terminal_closure_states
Create Date: 2026-04-20 14:36:55.312309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0022'
down_revision: Union[str, Sequence[str], None] = '0021_add_terminal_closure_states'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_advance_payment_client_record_period', 'advance_payments', ['client_record_id', 'period'], unique=False)
    op.create_index('uq_advance_payment_client_record_period_active', 'advance_payments', ['client_record_id', 'period'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('uq_annual_reports_client_record_tax_year'), table_name='annual_reports', postgresql_where='((deleted_at IS NULL) AND (client_record_id IS NOT NULL))')
    op.create_index('idx_annual_report_client_record_year', 'annual_reports', ['client_record_id', 'tax_year'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_authority_contact_client_record', 'authority_contacts', ['client_record_id'], unique=False)
    op.create_index('idx_binder_client_record', 'binders', ['client_record_id'], unique=False)
    op.drop_index(op.f('ix_business_legal_entity_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_legal_entity_id'), 'businesses', ['legal_entity_id'], unique=False)
    op.create_index('idx_charge_client_record_period', 'charges', ['client_record_id', 'period'], unique=False)
    op.create_index('idx_correspondence_client_record', 'correspondence_entries', ['client_record_id'], unique=False)
    op.add_column('legal_entities', sa.Column('official_name', sa.String(), nullable=True))
    op.create_index('ix_legal_entities_official_name', 'legal_entities', ['official_name'], unique=False)
    op.create_index('idx_notification_client_record_status', 'notifications', ['client_record_id', 'status'], unique=False)
    op.create_index('ix_permanent_documents_client_record_type_year', 'permanent_documents', ['client_record_id', 'document_type', 'tax_year'], unique=False)
    op.drop_index(op.f('ix_person_legal_entity_links_person_id'), table_name='person_legal_entity_links')
    op.create_index('idx_reminder_client_record_type', 'reminders', ['client_record_id', 'reminder_type'], unique=False)
    op.create_index('idx_sig_request_client_record', 'signature_requests', ['client_record_id'], unique=False)
    op.drop_index(op.f('uq_tax_deadlines_client_record_type_no_period'), table_name='tax_deadlines', postgresql_where='((deleted_at IS NULL) AND (period IS NULL) AND (client_record_id IS NOT NULL))')
    op.drop_index(op.f('uq_tax_deadlines_client_record_type_period'), table_name='tax_deadlines', postgresql_where='((deleted_at IS NULL) AND (period IS NOT NULL) AND (client_record_id IS NOT NULL))')
    op.create_index('idx_tax_deadline_client_record_period', 'tax_deadlines', ['client_record_id', 'period'], unique=False)
    op.drop_index(op.f('uq_vat_work_items_client_record_period'), table_name='vat_work_items', postgresql_where='((deleted_at IS NULL) AND (client_record_id IS NOT NULL))')
    op.create_index('uq_vat_work_item_client_record_period', 'vat_work_items', ['client_record_id', 'period'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_vat_work_item_client_record_period', table_name='vat_work_items', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('uq_vat_work_items_client_record_period'), 'vat_work_items', ['client_record_id', 'period'], unique=True, postgresql_where='((deleted_at IS NULL) AND (client_record_id IS NOT NULL))')
    op.drop_index('idx_tax_deadline_client_record_period', table_name='tax_deadlines')
    op.create_index(op.f('uq_tax_deadlines_client_record_type_period'), 'tax_deadlines', ['client_record_id', 'deadline_type', 'period'], unique=True, postgresql_where='((deleted_at IS NULL) AND (period IS NOT NULL) AND (client_record_id IS NOT NULL))')
    op.create_index(op.f('uq_tax_deadlines_client_record_type_no_period'), 'tax_deadlines', ['client_record_id', 'deadline_type'], unique=True, postgresql_where='((deleted_at IS NULL) AND (period IS NULL) AND (client_record_id IS NOT NULL))')
    op.drop_index('idx_sig_request_client_record', table_name='signature_requests')
    op.drop_index('idx_reminder_client_record_type', table_name='reminders')
    op.create_index(op.f('ix_person_legal_entity_links_person_id'), 'person_legal_entity_links', ['person_id'], unique=False)
    op.drop_index('ix_permanent_documents_client_record_type_year', table_name='permanent_documents')
    op.drop_index('idx_notification_client_record_status', table_name='notifications')
    op.drop_index('ix_legal_entities_official_name', table_name='legal_entities')
    op.drop_column('legal_entities', 'official_name')
    op.drop_index('idx_correspondence_client_record', table_name='correspondence_entries')
    op.drop_index('idx_charge_client_record_period', table_name='charges')
    op.drop_index(op.f('ix_businesses_legal_entity_id'), table_name='businesses')
    op.create_index(op.f('ix_business_legal_entity_id'), 'businesses', ['legal_entity_id'], unique=False)
    op.drop_index('idx_binder_client_record', table_name='binders')
    op.drop_index('idx_authority_contact_client_record', table_name='authority_contacts')
    op.drop_index('idx_annual_report_client_record_year', table_name='annual_reports', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('uq_annual_reports_client_record_tax_year'), 'annual_reports', ['client_record_id', 'tax_year'], unique=True, postgresql_where='((deleted_at IS NULL) AND (client_record_id IS NOT NULL))')
    op.drop_index('uq_advance_payment_client_record_period_active', table_name='advance_payments', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_advance_payment_client_record_period', table_name='advance_payments')
    # ### end Alembic commands ###
