"""remove client_id from businesses

Revision ID: 1d7068742798
Revises: 0023
Create Date: 2026-04-20 16:50:05.221868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7068742798'
down_revision: Union[str, Sequence[str], None] = '0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_client_id'), table_name='businesses')
    op.drop_index(op.f('ix_business_client_name_active'), table_name='businesses', postgresql_where='((business_name IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_index(op.f('ix_businesses_client_id'), table_name='businesses')
    op.create_index('ix_business_legal_entity_name_active', 'businesses', ['legal_entity_id', 'business_name'], unique=True, postgresql_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'))
    op.drop_constraint(op.f('businesses_client_id_fkey'), 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('businesses_client_id_fkey'), 'businesses', 'clients', ['client_id'], ['id'])
    op.drop_index('ix_business_legal_entity_name_active', table_name='businesses', postgresql_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'))
    op.create_index(op.f('ix_businesses_client_id'), 'businesses', ['client_id'], unique=False)
    op.create_index(op.f('ix_business_client_name_active'), 'businesses', ['client_id', 'business_name'], unique=True, postgresql_where='((business_name IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('ix_business_client_id'), 'businesses', ['client_id'], unique=False)
    # ### end Alembic commands ###
