"""add missing seed tables

Revision ID: 6392237139d9
Revises: 00fa037f8cb3
Create Date: 2026-04-21 16:23:32.875070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6392237139d9'
down_revision: Union[str, Sequence[str], None] = '00fa037f8cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_report_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('pension_contribution', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('donation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_credits', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('client_approved_at', sa.DateTime(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('amendment_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['annual_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('binder_intake_edit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['binder_intakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intake_edit_log_intake', 'binder_intake_edit_logs', ['intake_id'], unique=False)
    op.create_index(op.f('ix_binder_intake_edit_logs_intake_id'), 'binder_intake_edit_logs', ['intake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_binder_intake_edit_logs_intake_id'), table_name='binder_intake_edit_logs')
    op.drop_index('idx_intake_edit_log_intake', table_name='binder_intake_edit_logs')
    op.drop_table('binder_intake_edit_logs')
    op.drop_table('annual_report_details')
    # ### end Alembic commands ###
