"""0001_initial

Revision ID: 9074151726a8
Revises: 
Create Date: 2026-05-02 12:06:32.247587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9074151726a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reminder_status_send_on'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_advance_payment_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_annual_report_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_charge_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_tax_deadline_id'), table_name='reminders')
    op.drop_index(op.f('uq_reminder_tax_deadline_active'), table_name='reminders', postgresql_where="((status <> 'canceled'::reminderstatus) AND (deleted_at IS NULL) AND (tax_deadline_id IS NOT NULL))")
    op.drop_constraint(op.f('reminders_charge_id_fkey'), 'reminders', type_='foreignkey')
    op.drop_constraint(op.f('reminders_annual_report_id_fkey'), 'reminders', type_='foreignkey')
    op.drop_constraint(op.f('reminders_tax_deadline_id_fkey'), 'reminders', type_='foreignkey')
    op.drop_constraint(op.f('reminders_advance_payment_id_fkey'), 'reminders', type_='foreignkey')
    op.drop_column('reminders', 'charge_id')
    op.drop_column('reminders', 'tax_deadline_id')
    op.drop_column('reminders', 'advance_payment_id')
    op.drop_column('reminders', 'annual_report_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('annual_report_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reminders', sa.Column('advance_payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reminders', sa.Column('tax_deadline_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reminders', sa.Column('charge_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reminders_advance_payment_id_fkey'), 'reminders', 'advance_payments', ['advance_payment_id'], ['id'])
    op.create_foreign_key(op.f('reminders_tax_deadline_id_fkey'), 'reminders', 'tax_deadlines', ['tax_deadline_id'], ['id'])
    op.create_foreign_key(op.f('reminders_annual_report_id_fkey'), 'reminders', 'annual_reports', ['annual_report_id'], ['id'])
    op.create_foreign_key(op.f('reminders_charge_id_fkey'), 'reminders', 'charges', ['charge_id'], ['id'])
    op.create_index(op.f('uq_reminder_tax_deadline_active'), 'reminders', ['tax_deadline_id'], unique=True, postgresql_where="((status <> 'canceled'::reminderstatus) AND (deleted_at IS NULL) AND (tax_deadline_id IS NOT NULL))")
    op.create_index(op.f('ix_reminders_tax_deadline_id'), 'reminders', ['tax_deadline_id'], unique=False)
    op.create_index(op.f('ix_reminders_charge_id'), 'reminders', ['charge_id'], unique=False)
    op.create_index(op.f('ix_reminders_annual_report_id'), 'reminders', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_reminders_advance_payment_id'), 'reminders', ['advance_payment_id'], unique=False)
    op.create_index(op.f('idx_reminder_status_send_on'), 'reminders', ['status', 'send_on'], unique=False)
    # ### end Alembic commands ###
