"""0002_clean_reminder_model

Revision ID: ebf35ff3d75e
Revises: 9074151726a8
Create Date: 2026-05-02 12:42:49.362821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf35ff3d75e'
down_revision: Union[str, Sequence[str], None] = '9074151726a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Recreate reminder enums with only the types/statuses that remain after refactor.
    # PostgreSQL requires dropping dependent columns before altering enums; we rename+recreate.

    # 1. Delete system-generated reminder rows before shrinking enum
    op.execute("""
        DELETE FROM reminders
        WHERE reminder_type IN (
            'tax_deadline_approaching', 'vat_filing', 'advance_payment_due',
            'annual_report_deadline', 'unpaid_charge'
        )
    """)

    # 2. Shrink remindertype enum — remove system-generated types
    op.execute("ALTER TYPE remindertype RENAME TO remindertype_old")
    op.execute("CREATE TYPE remindertype AS ENUM ('binder_idle', 'document_missing', 'custom')")
    op.execute("""
        ALTER TABLE reminders
            ALTER COLUMN reminder_type TYPE remindertype
            USING reminder_type::text::remindertype
    """)
    op.execute("DROP TYPE remindertype_old")

    # 3. Shrink reminderstatus enum — remove PROCESSING
    op.execute("ALTER TYPE reminderstatus RENAME TO reminderstatus_old")
    op.execute("CREATE TYPE reminderstatus AS ENUM ('pending', 'sent', 'canceled')")
    op.execute("""
        ALTER TABLE reminders
            ALTER COLUMN status TYPE reminderstatus
            USING status::text::reminderstatus
    """)
    op.execute("DROP TYPE reminderstatus_old")

    # 4. Add unique partial index on manual-reminder uniqueness
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_reminder_active', 'reminders', ['client_record_id', 'reminder_type', 'target_date'], unique=True, postgresql_where=sa.text("status != 'canceled' AND deleted_at IS NULL"), sqlite_where=sa.text("status != 'canceled' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_reminder_active', table_name='reminders', postgresql_where=sa.text("status != 'canceled' AND deleted_at IS NULL"), sqlite_where=sa.text("status != 'canceled' AND deleted_at IS NULL"))

    op.execute("ALTER TYPE reminderstatus RENAME TO reminderstatus_old")
    op.execute("CREATE TYPE reminderstatus AS ENUM ('pending', 'processing', 'sent', 'canceled')")
    op.execute("ALTER TABLE reminders ALTER COLUMN status TYPE reminderstatus USING status::text::reminderstatus")
    op.execute("DROP TYPE reminderstatus_old")

    op.execute("ALTER TYPE remindertype RENAME TO remindertype_old")
    op.execute("""CREATE TYPE remindertype AS ENUM (
        'tax_deadline_approaching', 'vat_filing', 'advance_payment_due',
        'annual_report_deadline', 'binder_idle', 'unpaid_charge',
        'document_missing', 'custom'
    )""")
    op.execute("ALTER TABLE reminders ALTER COLUMN reminder_type TYPE remindertype USING reminder_type::text::remindertype")
    op.execute("DROP TYPE remindertype_old")
