"""initial_schema

Revision ID: f90ff6e80bcf
Revises: 
Create Date: 2026-03-21 17:24:28.881483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.utils.enum_utils import pg_enum
import app.utils.enum_utils

# revision identifiers, used by Alembic.
revision: str = 'f90ff6e80bcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('role', app.utils.enum_utils._NormalizedEnum('advisor', 'secretary', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('id_number', sa.String(), nullable=False),
    sa.Column('id_number_type', app.utils.enum_utils._NormalizedEnum('individual', 'corporation', 'passport', 'other', name='idnumbertype'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address_street', sa.String(), nullable=True),
    sa.Column('address_building_number', sa.String(), nullable=True),
    sa.Column('address_apartment', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_zip_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('restored_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_full_name', 'clients', ['full_name'], unique=False)
    op.create_index(op.f('ix_clients_id_number'), 'clients', ['id_number'], unique=False)
    op.create_index('ix_clients_id_number_active', 'clients', ['id_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('user_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', app.utils.enum_utils._NormalizedEnum('login_success', 'login_failure', 'logout', 'user_created', 'user_updated', 'user_activated', 'user_deactivated', 'password_reset', name='auditaction'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('success', 'failure', name='auditstatus'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_audit_logs_action'), 'user_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_actor_user_id'), 'user_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_created_at'), 'user_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_email'), 'user_audit_logs', ['email'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_status'), 'user_audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_target_user_id'), 'user_audit_logs', ['target_user_id'], unique=False)
    op.create_table('binders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('binder_number', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('in_office', 'ready_for_pickup', 'returned', name='binderstatus'), nullable=False),
    sa.Column('returned_at', sa.Date(), nullable=True),
    sa.Column('pickup_person_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_binder_unique', 'binders', ['binder_number'], unique=True, postgresql_where=sa.text("status != 'returned' AND deleted_at IS NULL"), sqlite_where=sa.text("status != 'returned' AND deleted_at IS NULL"))
    op.create_index('idx_binder_client', 'binders', ['client_id'], unique=False)
    op.create_index('idx_binder_period_start', 'binders', ['period_start'], unique=False)
    op.create_index('idx_binder_status', 'binders', ['status'], unique=False)
    op.create_index(op.f('ix_binders_client_id'), 'binders', ['client_id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('business_type', app.utils.enum_utils._NormalizedEnum('osek_patur', 'osek_murshe', 'company', 'employee', name='businesstype'), nullable=False),
    sa.Column('tax_id_number', sa.String(length=9), nullable=True),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('active', 'frozen', 'closed', name='businessstatus'), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('restored_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restored_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_assigned', 'businesses', ['assigned_to'], unique=False)
    op.create_index('ix_business_client_id', 'businesses', ['client_id'], unique=False)
    op.create_index('ix_business_client_name_active', 'businesses', ['client_id', 'business_name'], unique=True, postgresql_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ix_business_status', 'businesses', ['status'], unique=False)
    op.create_index('ix_business_tax_id', 'businesses', ['tax_id_number'], unique=True, postgresql_where=sa.text('tax_id_number IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('tax_id_number IS NOT NULL AND deleted_at IS NULL'))
    op.create_index(op.f('ix_businesses_client_id'), 'businesses', ['client_id'], unique=False)
    op.create_table('annual_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('client_type', app.utils.enum_utils._NormalizedEnum('individual', 'self_employed', 'corporation', 'partnership', name='clienttypeforreport'), nullable=False),
    sa.Column('form_type', app.utils.enum_utils._NormalizedEnum('1301', '1215', '6111', name='annualreportform'), nullable=False),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('not_started', 'collecting_docs', 'docs_complete', 'in_preparation', 'pending_client', 'submitted', 'amended', 'accepted', 'assessment_issued', 'objection_filed', 'closed', name='annualreportstatus'), nullable=False),
    sa.Column('deadline_type', app.utils.enum_utils._NormalizedEnum('standard', 'extended', 'custom', name='deadlinetype'), nullable=False),
    sa.Column('filing_deadline', sa.DateTime(), nullable=True),
    sa.Column('custom_deadline_note', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('ita_reference', sa.String(), nullable=True),
    sa.Column('assessment_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('refund_due', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_due', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('has_rental_income', sa.Boolean(), nullable=False),
    sa.Column('has_capital_gains', sa.Boolean(), nullable=False),
    sa.Column('has_foreign_income', sa.Boolean(), nullable=False),
    sa.Column('has_depreciation', sa.Boolean(), nullable=False),
    sa.Column('has_exempt_rental', sa.Boolean(), nullable=False),
    sa.Column('submission_method', app.utils.enum_utils._NormalizedEnum('online', 'manual', 'representative', name='submissionmethod'), nullable=True),
    sa.Column('extension_reason', app.utils.enum_utils._NormalizedEnum('military_service', 'health_reason', 'general', 'war_situation', name='extensionreason'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_annual_report_assigned', 'annual_reports', ['assigned_to'], unique=False)
    op.create_index('idx_annual_report_business_year', 'annual_reports', ['business_id', 'tax_year'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_annual_report_deadline', 'annual_reports', ['filing_deadline'], unique=False)
    op.create_index('idx_annual_report_status', 'annual_reports', ['status'], unique=False)
    op.create_index(op.f('ix_annual_reports_business_id'), 'annual_reports', ['business_id'], unique=False)
    op.create_table('authority_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', app.utils.enum_utils._NormalizedEnum('assessing_officer', 'vat_branch', 'national_insurance', 'other', name='contacttype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_authority_contact_business', 'authority_contacts', ['business_id'], unique=False)
    op.create_index('idx_authority_contact_type', 'authority_contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_authority_contacts_business_id'), 'authority_contacts', ['business_id'], unique=False)
    op.create_table('binder_intakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.Date(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_intakes_binder_id'), 'binder_intakes', ['binder_id'], unique=False)
    op.create_table('binder_status_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binder_status_logs_binder_id'), 'binder_status_logs', ['binder_id'], unique=False)
    op.create_table('business_tax_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('vat_type', app.utils.enum_utils._NormalizedEnum('monthly', 'bimonthly', 'exempt', name='vattype'), nullable=True),
    sa.Column('vat_start_date', sa.Date(), nullable=True),
    sa.Column('accountant_name', sa.String(length=100), nullable=True),
    sa.Column('vat_exempt_ceiling', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('advance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('advance_rate_updated_at', sa.Date(), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_tax_profiles_business_id'), 'business_tax_profiles', ['business_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=True),
    sa.Column('trigger', app.utils.enum_utils._NormalizedEnum('binder_received', 'binder_ready_for_pickup', 'manual_payment_reminder', name='notificationtrigger'), nullable=False),
    sa.Column('channel', app.utils.enum_utils._NormalizedEnum('whatsapp', 'email', name='notificationchannel'), nullable=False),
    sa.Column('severity', app.utils.enum_utils._NormalizedEnum('info', 'warning', 'urgent', 'critical', name='notificationseverity'), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('pending', 'sent', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_business_status', 'notifications', ['business_id', 'status'], unique=False)
    op.create_index('idx_notification_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_binder_id'), 'notifications', ['binder_id'], unique=False)
    op.create_index(op.f('ix_notifications_business_id'), 'notifications', ['business_id'], unique=False)
    op.create_table('vat_work_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('period_type', app.utils.enum_utils._NormalizedEnum('monthly', 'bimonthly', 'exempt', name='vattype'), nullable=False),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('pending_materials', 'material_received', 'data_entry_in_progress', 'ready_for_review', 'filed', name='vatworkitemstatus'), nullable=False),
    sa.Column('pending_materials_note', sa.Text(), nullable=True),
    sa.Column('total_output_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_input_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_output_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_input_net', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_justification', sa.Text(), nullable=True),
    sa.Column('submission_method', app.utils.enum_utils._NormalizedEnum('online', 'manual', 'representative', name='submissionmethod'), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('filed_by', sa.Integer(), nullable=True),
    sa.Column('submission_reference', sa.String(length=100), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('amends_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amends_item_id'], ['vat_work_items.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['filed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'period', name='uq_vat_work_item_business_period')
    )
    op.create_index(op.f('ix_vat_work_items_business_id'), 'vat_work_items', ['business_id'], unique=False)
    op.create_index('ix_vat_work_items_period', 'vat_work_items', ['period'], unique=False)
    op.create_index('ix_vat_work_items_status', 'vat_work_items', ['status'], unique=False)
    op.create_table('advance_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('period_months_count', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('pending', 'paid', 'partial', 'overdue', name='advancepaymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', app.utils.enum_utils._NormalizedEnum('bank_transfer', 'credit_card', 'check', 'direct_debit', 'cash', 'other', name='paymentmethod'), nullable=True),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'period', name='uq_advance_payment_business_period')
    )
    op.create_index('idx_advance_payment_business_period', 'advance_payments', ['business_id', 'period'], unique=False)
    op.create_index('idx_advance_payment_due_date', 'advance_payments', ['due_date'], unique=False)
    op.create_index('idx_advance_payment_status', 'advance_payments', ['status'], unique=False)
    op.create_index(op.f('ix_advance_payments_annual_report_id'), 'advance_payments', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_advance_payments_business_id'), 'advance_payments', ['business_id'], unique=False)
    op.create_table('annual_report_annex_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('schedule', app.utils.enum_utils._NormalizedEnum('schedule_b', 'schedule_bet', 'schedule_gimmel', 'schedule_dalet', 'schedule_heh', 'schedule_a', 'schedule_vav', 'annex_15', 'annex_867', name='annualreportschedule'), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_report_annex_data_annual_report_id'), 'annual_report_annex_data', ['annual_report_id'], unique=False)
    op.create_table('annual_report_credit_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('reason', app.utils.enum_utils._NormalizedEnum('resident', 'academic_degree', 'discharged_soldier', 'new_immigrant', 'single_parent', name='creditpointreason'), nullable=False),
    sa.Column('points', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annual_report_id', 'reason', name='uq_credit_point_report_reason')
    )
    op.create_index(op.f('ix_annual_report_credit_points_annual_report_id'), 'annual_report_credit_points', ['annual_report_id'], unique=False)
    op.create_table('annual_report_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('pension_contribution', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('donation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_credits', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('client_approved_at', sa.DateTime(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('amendment_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['annual_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('annual_report_income_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('source_type', app.utils.enum_utils._NormalizedEnum('business', 'salary', 'interest', 'dividends', 'capital_gains', 'rental', 'foreign', 'pension', 'other', name='incomesourcetype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_report_income_lines_annual_report_id'), 'annual_report_income_lines', ['annual_report_id'], unique=False)
    op.create_table('annual_report_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('schedule', app.utils.enum_utils._NormalizedEnum('schedule_b', 'schedule_bet', 'schedule_gimmel', 'schedule_dalet', 'schedule_heh', 'schedule_a', 'schedule_vav', 'annex_15', 'annex_867', name='annualreportschedule'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_report_schedules_annual_report_id'), 'annual_report_schedules', ['annual_report_id'], unique=False)
    op.create_table('annual_report_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('from_status', app.utils.enum_utils._NormalizedEnum('not_started', 'collecting_docs', 'docs_complete', 'in_preparation', 'pending_client', 'submitted', 'amended', 'accepted', 'assessment_issued', 'objection_filed', 'closed', name='annualreportstatus'), nullable=True),
    sa.Column('to_status', app.utils.enum_utils._NormalizedEnum('not_started', 'collecting_docs', 'docs_complete', 'in_preparation', 'pending_client', 'submitted', 'amended', 'accepted', 'assessment_issued', 'objection_filed', 'closed', name='annualreportstatus'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_report_status_history_annual_report_id'), 'annual_report_status_history', ['annual_report_id'], unique=False)
    op.create_table('authority_contact_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['authority_contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'client_id', 'business_id', name='uq_authority_contact_link')
    )
    op.create_index(op.f('ix_authority_contact_links_business_id'), 'authority_contact_links', ['business_id'], unique=False)
    op.create_index(op.f('ix_authority_contact_links_client_id'), 'authority_contact_links', ['client_id'], unique=False)
    op.create_index(op.f('ix_authority_contact_links_contact_id'), 'authority_contact_links', ['contact_id'], unique=False)
    op.create_table('binder_intake_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('material_type', app.utils.enum_utils._NormalizedEnum('vat', 'income_tax', 'annual_report', 'salary', 'bookkeeping', 'national_insurance', 'capital_declaration', 'pension_and_insurance', 'corporate_docs', 'tax_assessment', 'other', name='materialtype'), nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['binder_intakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intake_material_business', 'binder_intake_materials', ['business_id'], unique=False)
    op.create_index('idx_intake_material_type', 'binder_intake_materials', ['material_type'], unique=False)
    op.create_index(op.f('ix_binder_intake_materials_annual_report_id'), 'binder_intake_materials', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_binder_intake_materials_business_id'), 'binder_intake_materials', ['business_id'], unique=False)
    op.create_index(op.f('ix_binder_intake_materials_intake_id'), 'binder_intake_materials', ['intake_id'], unique=False)
    op.create_table('charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('charge_type', app.utils.enum_utils._NormalizedEnum('monthly_retainer', 'annual_report_fee', 'vat_filing_fee', 'representation_fee', 'consultation_fee', 'other', name='chargetype'), nullable=False),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('draft', 'issued', 'paid', 'canceled', name='chargestatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('months_covered', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.Integer(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['canceled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_charge_business_period', 'charges', ['business_id', 'period'], unique=False)
    op.create_index('idx_charge_status', 'charges', ['status'], unique=False)
    op.create_index(op.f('ix_charges_annual_report_id'), 'charges', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_charges_business_id'), 'charges', ['business_id'], unique=False)
    op.create_index(op.f('ix_charges_period'), 'charges', ['period'], unique=False)
    op.create_table('correspondence_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('correspondence_type', app.utils.enum_utils._NormalizedEnum('call', 'letter', 'email', 'meeting', name='correspondencetype'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['authority_contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_correspondence_business', 'correspondence_entries', ['business_id'], unique=False)
    op.create_index('idx_correspondence_business_occurred', 'correspondence_entries', ['business_id', 'occurred_at'], unique=False)
    op.create_index('idx_correspondence_occurred', 'correspondence_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_correspondence_entries_business_id'), 'correspondence_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_correspondence_entries_contact_id'), 'correspondence_entries', ['contact_id'], unique=False)
    op.create_table('permanent_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('scope', app.utils.enum_utils._NormalizedEnum('client', 'business', name='documentscope'), nullable=False),
    sa.Column('document_type', app.utils.enum_utils._NormalizedEnum('id_copy', 'power_of_attorney', 'engagement_agreement', 'tax_form', 'receipt', 'invoice_doc', 'bank_approval', 'withholding_certificate', 'nii_approval', 'other', name='documenttype'), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('tax_year', sa.SmallInteger(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('pending', 'received', 'approved', 'rejected', name='documentstatus'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(scope = 'client') OR (scope = 'business' AND business_id IS NOT NULL)", name='ck_document_business_scope_requires_business_id'),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['permanent_documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permanent_documents_business', 'permanent_documents', ['business_id', 'document_type', 'tax_year'], unique=False)
    op.create_index(op.f('ix_permanent_documents_business_id'), 'permanent_documents', ['business_id'], unique=False)
    op.create_index(op.f('ix_permanent_documents_client_id'), 'permanent_documents', ['client_id'], unique=False)
    op.create_index('ix_permanent_documents_client_type_year', 'permanent_documents', ['client_id', 'document_type', 'tax_year'], unique=False)
    op.create_index(op.f('ix_permanent_documents_tax_year'), 'permanent_documents', ['tax_year'], unique=False)
    op.create_table('vat_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('invoice_type', app.utils.enum_utils._NormalizedEnum('income', 'expense', name='invoicetype'), nullable=False),
    sa.Column('document_type', app.utils.enum_utils._NormalizedEnum('tax_invoice', 'transaction_invoice', 'receipt', 'consolidated', 'self_invoice', 'credit_note', name='documenttype'), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('counterparty_name', sa.String(), nullable=False),
    sa.Column('counterparty_id', sa.String(), nullable=True),
    sa.Column('counterparty_id_type', app.utils.enum_utils._NormalizedEnum('il_business', 'il_personal', 'foreign', 'anonymous', name='counterpartyidtype'), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_category', app.utils.enum_utils._NormalizedEnum('office', 'travel', 'professional_services', 'equipment', 'rent', 'salary', 'marketing', 'vehicle', 'fuel', 'vehicle_maintenance', 'vehicle_insurance', 'vehicle_leasing', 'tolls_and_parking', 'entertainment', 'gifts', 'communication', 'insurance', 'maintenance', 'municipal_tax', 'utilities', 'postage_and_shipping', 'bank_fees', 'mixed_expense', 'other', name='expensecategory'), nullable=True),
    sa.Column('rate_type', app.utils.enum_utils._NormalizedEnum('standard', 'exempt', 'zero_rate', name='vatratetype'), nullable=False),
    sa.Column('deduction_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_exceptional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['vat_work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'invoice_type', 'invoice_number', name='uq_vat_invoice_item_type_number')
    )
    op.create_index('ix_vat_invoices_date', 'vat_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_vat_invoices_work_item_id'), 'vat_invoices', ['work_item_id'], unique=False)
    op.create_index('ix_vat_invoices_work_item_type', 'vat_invoices', ['work_item_id', 'invoice_type'], unique=False)
    op.create_table('annual_report_expense_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=False),
    sa.Column('category', app.utils.enum_utils._NormalizedEnum('office_rent', 'professional_services', 'salaries', 'depreciation', 'vehicle', 'marketing', 'insurance', 'communication', 'travel', 'training', 'bank_fees', 'other', name='expensecategorytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recognition_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('supporting_document_ref', sa.String(length=255), nullable=True),
    sa.Column('supporting_document_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['supporting_document_id'], ['permanent_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_report_expense_lines_annual_report_id'), 'annual_report_expense_lines', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_annual_report_expense_lines_supporting_document_id'), 'annual_report_expense_lines', ['supporting_document_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_invoice_id', sa.String(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_charge_id'), 'invoices', ['charge_id'], unique=True)
    op.create_table('signature_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('request_type', app.utils.enum_utils._NormalizedEnum('engagement_agreement', 'annual_report_approval', 'power_of_attorney', 'vat_return_approval', 'custom', name='signaturerequesttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('signer_name', sa.String(), nullable=False),
    sa.Column('signer_email', sa.String(), nullable=True),
    sa.Column('signer_phone', sa.String(), nullable=True),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('draft', 'pending_signature', 'signed', 'declined', 'expired', 'canceled', name='signaturerequeststatus'), nullable=False),
    sa.Column('signing_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('signer_ip_address', sa.String(), nullable=True),
    sa.Column('signer_user_agent', sa.String(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('signed_document_key', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['canceled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['permanent_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sig_request_annual_report', 'signature_requests', ['annual_report_id'], unique=False)
    op.create_index('idx_sig_request_business', 'signature_requests', ['business_id'], unique=False)
    op.create_index('idx_sig_request_status', 'signature_requests', ['status'], unique=False)
    op.create_index('idx_sig_request_token', 'signature_requests', ['signing_token'], unique=False)
    op.create_index(op.f('ix_signature_requests_annual_report_id'), 'signature_requests', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_business_id'), 'signature_requests', ['business_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_signing_token'), 'signature_requests', ['signing_token'], unique=True)
    op.create_table('tax_deadlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('deadline_type', app.utils.enum_utils._NormalizedEnum('vat', 'advance_payment', 'national_insurance', 'annual_report', 'other', name='deadlinetype'), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('pending', 'completed', name='taxdeadlinestatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('advance_payment_id', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advance_payment_id'], ['advance_payments.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_deadline_business_period', 'tax_deadlines', ['business_id', 'period'], unique=False)
    op.create_index('idx_tax_deadline_status', 'tax_deadlines', ['status'], unique=False)
    op.create_index('idx_tax_deadline_type', 'tax_deadlines', ['deadline_type'], unique=False)
    op.create_index(op.f('ix_tax_deadlines_advance_payment_id'), 'tax_deadlines', ['advance_payment_id'], unique=False)
    op.create_index(op.f('ix_tax_deadlines_business_id'), 'tax_deadlines', ['business_id'], unique=False)
    op.create_index(op.f('ix_tax_deadlines_due_date'), 'tax_deadlines', ['due_date'], unique=False)
    op.create_table('vat_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['vat_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['vat_work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_audit_logs_invoice_id'), 'vat_audit_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_vat_audit_logs_work_item_id'), 'vat_audit_logs', ['work_item_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', app.utils.enum_utils._NormalizedEnum('tax_deadline_approaching', 'vat_filing', 'advance_payment_due', 'annual_report_deadline', 'binder_idle', 'unpaid_charge', 'document_missing', 'custom', name='remindertype'), nullable=False),
    sa.Column('status', app.utils.enum_utils._NormalizedEnum('pending', 'sent', 'canceled', name='reminderstatus'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('send_on', sa.Date(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('binder_id', sa.Integer(), nullable=True),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('tax_deadline_id', sa.Integer(), nullable=True),
    sa.Column('annual_report_id', sa.Integer(), nullable=True),
    sa.Column('advance_payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advance_payment_id'], ['advance_payments.id'], ),
    sa.ForeignKeyConstraint(['annual_report_id'], ['annual_reports.id'], ),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['canceled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['charge_id'], ['charges.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tax_deadline_id'], ['tax_deadlines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminder_business_type', 'reminders', ['business_id', 'reminder_type'], unique=False)
    op.create_index('idx_reminder_status_send_on', 'reminders', ['status', 'send_on'], unique=False)
    op.create_index(op.f('ix_reminders_advance_payment_id'), 'reminders', ['advance_payment_id'], unique=False)
    op.create_index(op.f('ix_reminders_annual_report_id'), 'reminders', ['annual_report_id'], unique=False)
    op.create_index(op.f('ix_reminders_binder_id'), 'reminders', ['binder_id'], unique=False)
    op.create_index(op.f('ix_reminders_business_id'), 'reminders', ['business_id'], unique=False)
    op.create_index(op.f('ix_reminders_charge_id'), 'reminders', ['charge_id'], unique=False)
    op.create_index(op.f('ix_reminders_send_on'), 'reminders', ['send_on'], unique=False)
    op.create_index(op.f('ix_reminders_tax_deadline_id'), 'reminders', ['tax_deadline_id'], unique=False)
    op.create_table('signature_audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signature_request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signature_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sig_audit_occurred', 'signature_audit_events', ['occurred_at'], unique=False)
    op.create_index('idx_sig_audit_request', 'signature_audit_events', ['signature_request_id'], unique=False)
    op.create_index(op.f('ix_signature_audit_events_signature_request_id'), 'signature_audit_events', ['signature_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_audit_events_signature_request_id'), table_name='signature_audit_events')
    op.drop_index('idx_sig_audit_request', table_name='signature_audit_events')
    op.drop_index('idx_sig_audit_occurred', table_name='signature_audit_events')
    op.drop_table('signature_audit_events')
    op.drop_index(op.f('ix_reminders_tax_deadline_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_send_on'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_charge_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_business_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_binder_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_annual_report_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_advance_payment_id'), table_name='reminders')
    op.drop_index('idx_reminder_status_send_on', table_name='reminders')
    op.drop_index('idx_reminder_business_type', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_vat_audit_logs_work_item_id'), table_name='vat_audit_logs')
    op.drop_index(op.f('ix_vat_audit_logs_invoice_id'), table_name='vat_audit_logs')
    op.drop_table('vat_audit_logs')
    op.drop_index(op.f('ix_tax_deadlines_due_date'), table_name='tax_deadlines')
    op.drop_index(op.f('ix_tax_deadlines_business_id'), table_name='tax_deadlines')
    op.drop_index(op.f('ix_tax_deadlines_advance_payment_id'), table_name='tax_deadlines')
    op.drop_index('idx_tax_deadline_type', table_name='tax_deadlines')
    op.drop_index('idx_tax_deadline_status', table_name='tax_deadlines')
    op.drop_index('idx_tax_deadline_business_period', table_name='tax_deadlines')
    op.drop_table('tax_deadlines')
    op.drop_index(op.f('ix_signature_requests_signing_token'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_business_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_annual_report_id'), table_name='signature_requests')
    op.drop_index('idx_sig_request_token', table_name='signature_requests')
    op.drop_index('idx_sig_request_status', table_name='signature_requests')
    op.drop_index('idx_sig_request_business', table_name='signature_requests')
    op.drop_index('idx_sig_request_annual_report', table_name='signature_requests')
    op.drop_table('signature_requests')
    op.drop_index(op.f('ix_invoices_charge_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_annual_report_expense_lines_supporting_document_id'), table_name='annual_report_expense_lines')
    op.drop_index(op.f('ix_annual_report_expense_lines_annual_report_id'), table_name='annual_report_expense_lines')
    op.drop_table('annual_report_expense_lines')
    op.drop_index('ix_vat_invoices_work_item_type', table_name='vat_invoices')
    op.drop_index(op.f('ix_vat_invoices_work_item_id'), table_name='vat_invoices')
    op.drop_index('ix_vat_invoices_date', table_name='vat_invoices')
    op.drop_table('vat_invoices')
    op.drop_index(op.f('ix_permanent_documents_tax_year'), table_name='permanent_documents')
    op.drop_index('ix_permanent_documents_client_type_year', table_name='permanent_documents')
    op.drop_index(op.f('ix_permanent_documents_client_id'), table_name='permanent_documents')
    op.drop_index(op.f('ix_permanent_documents_business_id'), table_name='permanent_documents')
    op.drop_index('ix_permanent_documents_business', table_name='permanent_documents')
    op.drop_table('permanent_documents')
    op.drop_index(op.f('ix_correspondence_entries_contact_id'), table_name='correspondence_entries')
    op.drop_index(op.f('ix_correspondence_entries_business_id'), table_name='correspondence_entries')
    op.drop_index('idx_correspondence_occurred', table_name='correspondence_entries')
    op.drop_index('idx_correspondence_business_occurred', table_name='correspondence_entries')
    op.drop_index('idx_correspondence_business', table_name='correspondence_entries')
    op.drop_table('correspondence_entries')
    op.drop_index(op.f('ix_charges_period'), table_name='charges')
    op.drop_index(op.f('ix_charges_business_id'), table_name='charges')
    op.drop_index(op.f('ix_charges_annual_report_id'), table_name='charges')
    op.drop_index('idx_charge_status', table_name='charges')
    op.drop_index('idx_charge_business_period', table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_binder_intake_materials_intake_id'), table_name='binder_intake_materials')
    op.drop_index(op.f('ix_binder_intake_materials_business_id'), table_name='binder_intake_materials')
    op.drop_index(op.f('ix_binder_intake_materials_annual_report_id'), table_name='binder_intake_materials')
    op.drop_index('idx_intake_material_type', table_name='binder_intake_materials')
    op.drop_index('idx_intake_material_business', table_name='binder_intake_materials')
    op.drop_table('binder_intake_materials')
    op.drop_index(op.f('ix_authority_contact_links_contact_id'), table_name='authority_contact_links')
    op.drop_index(op.f('ix_authority_contact_links_client_id'), table_name='authority_contact_links')
    op.drop_index(op.f('ix_authority_contact_links_business_id'), table_name='authority_contact_links')
    op.drop_table('authority_contact_links')
    op.drop_index(op.f('ix_annual_report_status_history_annual_report_id'), table_name='annual_report_status_history')
    op.drop_table('annual_report_status_history')
    op.drop_index(op.f('ix_annual_report_schedules_annual_report_id'), table_name='annual_report_schedules')
    op.drop_table('annual_report_schedules')
    op.drop_index(op.f('ix_annual_report_income_lines_annual_report_id'), table_name='annual_report_income_lines')
    op.drop_table('annual_report_income_lines')
    op.drop_table('annual_report_details')
    op.drop_index(op.f('ix_annual_report_credit_points_annual_report_id'), table_name='annual_report_credit_points')
    op.drop_table('annual_report_credit_points')
    op.drop_index(op.f('ix_annual_report_annex_data_annual_report_id'), table_name='annual_report_annex_data')
    op.drop_table('annual_report_annex_data')
    op.drop_index(op.f('ix_advance_payments_business_id'), table_name='advance_payments')
    op.drop_index(op.f('ix_advance_payments_annual_report_id'), table_name='advance_payments')
    op.drop_index('idx_advance_payment_status', table_name='advance_payments')
    op.drop_index('idx_advance_payment_due_date', table_name='advance_payments')
    op.drop_index('idx_advance_payment_business_period', table_name='advance_payments')
    op.drop_table('advance_payments')
    op.drop_index('ix_vat_work_items_status', table_name='vat_work_items')
    op.drop_index('ix_vat_work_items_period', table_name='vat_work_items')
    op.drop_index(op.f('ix_vat_work_items_business_id'), table_name='vat_work_items')
    op.drop_table('vat_work_items')
    op.drop_index(op.f('ix_notifications_business_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_binder_id'), table_name='notifications')
    op.drop_index('idx_notification_created_at', table_name='notifications')
    op.drop_index('idx_notification_business_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_business_tax_profiles_business_id'), table_name='business_tax_profiles')
    op.drop_table('business_tax_profiles')
    op.drop_index(op.f('ix_binder_status_logs_binder_id'), table_name='binder_status_logs')
    op.drop_table('binder_status_logs')
    op.drop_index(op.f('ix_binder_intakes_binder_id'), table_name='binder_intakes')
    op.drop_table('binder_intakes')
    op.drop_index(op.f('ix_authority_contacts_business_id'), table_name='authority_contacts')
    op.drop_index('idx_authority_contact_type', table_name='authority_contacts')
    op.drop_index('idx_authority_contact_business', table_name='authority_contacts')
    op.drop_table('authority_contacts')
    op.drop_index(op.f('ix_annual_reports_business_id'), table_name='annual_reports')
    op.drop_index('idx_annual_report_status', table_name='annual_reports')
    op.drop_index('idx_annual_report_deadline', table_name='annual_reports')
    op.drop_index('idx_annual_report_business_year', table_name='annual_reports', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_annual_report_assigned', table_name='annual_reports')
    op.drop_table('annual_reports')
    op.drop_index(op.f('ix_businesses_client_id'), table_name='businesses')
    op.drop_index('ix_business_tax_id', table_name='businesses', postgresql_where=sa.text('tax_id_number IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('tax_id_number IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('ix_business_status', table_name='businesses')
    op.drop_index('ix_business_client_name_active', table_name='businesses', postgresql_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'), sqlite_where=sa.text('business_name IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('ix_business_client_id', table_name='businesses')
    op.drop_index('ix_business_assigned', table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_binders_client_id'), table_name='binders')
    op.drop_index('idx_binder_status', table_name='binders')
    op.drop_index('idx_binder_period_start', table_name='binders')
    op.drop_index('idx_binder_client', table_name='binders')
    op.drop_index('idx_active_binder_unique', table_name='binders', postgresql_where=sa.text("status != 'returned' AND deleted_at IS NULL"), sqlite_where=sa.text("status != 'returned' AND deleted_at IS NULL"))
    op.drop_table('binders')
    op.drop_index(op.f('ix_user_audit_logs_target_user_id'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_status'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_email'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_created_at'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_actor_user_id'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_action'), table_name='user_audit_logs')
    op.drop_table('user_audit_logs')
    op.drop_index('ix_clients_id_number_active', table_name='clients', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_clients_id_number'), table_name='clients')
    op.drop_index('ix_clients_full_name', table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
