from .annual_reports import ANNUAL_REPORT_RULES_V2
from .income_tax import (
    ANNUAL_REPORT_ATTACHMENTS,
    ANNUAL_REPORT_RULES,
    INCOME_TAX_ADVANCE_RULES,
)
from .national_insurance import NATIONAL_INSURANCE_RULES
from .vat import VAT_RULES
from .withholding import WITHHOLDING_RULES

__all__ = [
    "VAT_RULES",
    "INCOME_TAX_ADVANCE_RULES",
    "ANNUAL_REPORT_RULES",
    "ANNUAL_REPORT_ATTACHMENTS",
    "NATIONAL_INSURANCE_RULES",
    "WITHHOLDING_RULES",
    "ANNUAL_REPORT_RULES_V2",
]
